RESEARCH_LIST_STOCKS = [
    {'symbol': '360ONE', 'company_name': '360 ONE WAM Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': '3MINDIA', 'company_name': '3M India Ltd.', 'asset_type': 'stocks', 'sector': 'Diversified'},
    {'symbol': 'AADHARHFC', 'company_name': 'Aadhar Housing Finance Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'AARTIIND', 'company_name': 'Aarti Industries Ltd.', 'asset_type': 'stocks', 'sector': 'Chemicals'},
    {'symbol': 'AAVAS', 'company_name': 'Aavas Financiers Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'ABB', 'company_name': 'ABB India Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'ABBOTINDIA', 'company_name': 'Abbott India Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'ABCAPITAL', 'company_name': 'Aditya Birla Capital Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'ABFRL', 'company_name': 'Aditya Birla Fashion and Retail Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Services'},
    {'symbol': 'ABLBL', 'company_name': 'Aditya Birla Lifestyle Brands Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Services'},
    {'symbol': 'ABREL', 'company_name': 'Aditya Birla Real Estate Ltd.', 'asset_type': 'stocks', 'sector': 'Forest Materials'},
    {'symbol': 'ABSLAMC', 'company_name': 'Aditya Birla Sun Life AMC Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'ACC', 'company_name': 'ACC Ltd.', 'asset_type': 'stocks', 'sector': 'Construction Materials'},
    {'symbol': 'ACE', 'company_name': 'Action Construction Equipment Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'ACMESOLAR', 'company_name': 'ACME Solar Holdings Ltd.', 'asset_type': 'stocks', 'sector': 'Power'},
    {'symbol': 'ADANIENSOL', 'company_name': 'Adani Energy Solutions Ltd.', 'asset_type': 'stocks', 'sector': 'Power'},
    {'symbol': 'ADANIENT', 'company_name': 'Adani Enterprises Ltd.', 'asset_type': 'stocks', 'sector': 'Metals & Mining'},
    {'symbol': 'ADANIGREEN', 'company_name': 'Adani Green Energy Ltd.', 'asset_type': 'stocks', 'sector': 'Power'},
    {'symbol': 'ADANIPORTS', 'company_name': 'Adani Ports and Special Economic Zone Ltd.', 'asset_type': 'stocks', 'sector': 'Services'},
    {'symbol': 'ADANIPOWER', 'company_name': 'Adani Power Ltd.', 'asset_type': 'stocks', 'sector': 'Power'},
    {'symbol': 'AEGISLOG', 'company_name': 'Aegis Logistics Ltd.', 'asset_type': 'stocks', 'sector': 'Oil Gas & Consumable Fuels'},
    {'symbol': 'AEGISVOPAK', 'company_name': 'Aegis Vopak Terminals Ltd.', 'asset_type': 'stocks', 'sector': 'Oil Gas & Consumable Fuels'},
    {'symbol': 'AFCONS', 'company_name': 'Afcons Infrastructure Ltd.', 'asset_type': 'stocks', 'sector': 'Construction'},
    {'symbol': 'AFFLE', 'company_name': 'Affle 3i Ltd.', 'asset_type': 'stocks', 'sector': 'Information Technology'},
    {'symbol': 'AGARWALEYE', 'company_name': "Dr. Agarwal's Health Care Ltd.", 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'AIAENG', 'company_name': 'AIA Engineering Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'AIIL', 'company_name': 'Authum Investment & Infrastructure Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'AJANTPHARM', 'company_name': 'Ajanta Pharmaceuticals Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'AKUMS', 'company_name': 'Akums Drugs and Pharmaceuticals Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'AKZOINDIA', 'company_name': 'Akzo Nobel India Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Durables'},
    {'symbol': 'ALKEM', 'company_name': 'Alkem Laboratories Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'ALKYLAMINE', 'company_name': 'Alkyl Amines Chemicals Ltd.', 'asset_type': 'stocks', 'sector': 'Chemicals'},
    {'symbol': 'ALOKINDS', 'company_name': 'Alok Industries Ltd.', 'asset_type': 'stocks', 'sector': 'Textiles'},
    {'symbol': 'AMBER', 'company_name': 'Amber Enterprises India Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Durables'},
    {'symbol': 'AMBUJACEM', 'company_name': 'Ambuja Cements Ltd.', 'asset_type': 'stocks', 'sector': 'Construction Materials'},
    {'symbol': 'ANANDRATHI', 'company_name': 'Anand Rathi Wealth Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'ANANTRAJ', 'company_name': 'Anant Raj Ltd.', 'asset_type': 'stocks', 'sector': 'Realty'},
    {'symbol': 'ANGELONE', 'company_name': 'Angel One Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'APARINDS', 'company_name': 'Apar Industries Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'APLAPOLLO', 'company_name': 'APL Apollo Tubes Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'APLLTD', 'company_name': 'Alembic Pharmaceuticals Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'APOLLOHOSP', 'company_name': 'Apollo Hospitals Enterprise Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'APOLLOTYRE', 'company_name': 'Apollo Tyres Ltd.', 'asset_type': 'stocks', 'sector': 'Automobile and Auto Components'},
    {'symbol': 'APTUS', 'company_name': 'Aptus Value Housing Finance India Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'ARE&M', 'company_name': 'Amara Raja Energy & Mobility Ltd.', 'asset_type': 'stocks', 'sector': 'Automobile and Auto Components'},
    {'symbol': 'ASAHIINDIA', 'company_name': 'Asahi India Glass Ltd.', 'asset_type': 'stocks', 'sector': 'Automobile and Auto Components'},
    {'symbol': 'ASHOKLEY', 'company_name': 'Ashok Leyland Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'ASIANPAINT', 'company_name': 'Asian Paints Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Durables'},
    {'symbol': 'ASTERDM', 'company_name': 'Aster DM Healthcare Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'ASTRAL', 'company_name': 'Astral Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'ASTRAZEN', 'company_name': 'AstraZenca Pharma India Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'ATGL', 'company_name': 'Adani Total Gas Ltd.', 'asset_type': 'stocks', 'sector': 'Oil Gas & Consumable Fuels'},
    {'symbol': 'ATHERENERG', 'company_name': 'Ather Energy Ltd.', 'asset_type': 'stocks', 'sector': 'Automobile and Auto Components'},
    {'symbol': 'ATUL', 'company_name': 'Atul Ltd.', 'asset_type': 'stocks', 'sector': 'Chemicals'},
    {'symbol': 'AUBANK', 'company_name': 'AU Small Finance Bank Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'AUROPHARMA', 'company_name': 'Aurobindo Pharma Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'AWL', 'company_name': 'AWL Agri Business Ltd.', 'asset_type': 'stocks', 'sector': 'Fast Moving Consumer Goods'},
    {'symbol': 'AXISBANK', 'company_name': 'Axis Bank Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'BAJAJ-AUTO', 'company_name': 'Bajaj Auto Ltd.', 'asset_type': 'stocks', 'sector': 'Automobile and Auto Components'},
    {'symbol': 'BAJAJFINSV', 'company_name': 'Bajaj Finserv Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'BAJAJHFL', 'company_name': 'Bajaj Housing Finance Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'BAJAJHLDNG', 'company_name': 'Bajaj Holdings & Investment Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'BAJFINANCE', 'company_name': 'Bajaj Finance Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'BALKRISIND', 'company_name': 'Balkrishna Industries Ltd.', 'asset_type': 'stocks', 'sector': 'Automobile and Auto Components'},
    {'symbol': 'BALRAMCHIN', 'company_name': 'Balrampur Chini Mills Ltd.', 'asset_type': 'stocks', 'sector': 'Fast Moving Consumer Goods'},
    {'symbol': 'BANDHANBNK', 'company_name': 'Bandhan Bank Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'BANKBARODA', 'company_name': 'Bank of Baroda', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'BANKINDIA', 'company_name': 'Bank of India', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'BASF', 'company_name': 'BASF India Ltd.', 'asset_type': 'stocks', 'sector': 'Chemicals'},
    {'symbol': 'BATAINDIA', 'company_name': 'Bata India Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Durables'},
    {'symbol': 'BAYERCROP', 'company_name': 'Bayer Cropscience Ltd.', 'asset_type': 'stocks', 'sector': 'Chemicals'},
    {'symbol': 'BBTC', 'company_name': 'Bombay Burmah Trading Corporation Ltd.', 'asset_type': 'stocks', 'sector': 'Fast Moving Consumer Goods'},
    {'symbol': 'BDL', 'company_name': 'Bharat Dynamics Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'BEL', 'company_name': 'Bharat Electronics Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'BEML', 'company_name': 'BEML Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'BERGEPAINT', 'company_name': 'Berger Paints India Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Durables'},
    {'symbol': 'BHARATFORG', 'company_name': 'Bharat Forge Ltd.', 'asset_type': 'stocks', 'sector': 'Automobile and Auto Components'},
    {'symbol': 'BHARTIARTL', 'company_name': 'Bharti Airtel Ltd.', 'asset_type': 'stocks', 'sector': 'Telecommunication'},
    {'symbol': 'BHARTIHEXA', 'company_name': 'Bharti Hexacom Ltd.', 'asset_type': 'stocks', 'sector': 'Telecommunication'},
    {'symbol': 'BHEL', 'company_name': 'Bharat Heavy Electricals Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'BIKAJI', 'company_name': 'Bikaji Foods International Ltd.', 'asset_type': 'stocks', 'sector': 'Fast Moving Consumer Goods'},
    {'symbol': 'BIOCON', 'company_name': 'Biocon Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'BLS', 'company_name': 'BLS International Services Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Services'},
    {'symbol': 'BLUEDART', 'company_name': 'Blue Dart Express Ltd.', 'asset_type': 'stocks', 'sector': 'Services'},
    {'symbol': 'BLUEJET', 'company_name': 'Blue Jet Healthcare Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'BLUESTARCO', 'company_name': 'Blue Star Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Durables'},
    {'symbol': 'BOSCHLTD', 'company_name': 'Bosch Ltd.', 'asset_type': 'stocks', 'sector': 'Automobile and Auto Components'},
    {'symbol': 'BPCL', 'company_name': 'Bharat Petroleum Corporation Ltd.', 'asset_type': 'stocks', 'sector': 'Oil Gas & Consumable Fuels'},
    {'symbol': 'BRIGADE', 'company_name': 'Brigade Enterprises Ltd.', 'asset_type': 'stocks', 'sector': 'Realty'},
    {'symbol': 'BRITANNIA', 'company_name': 'Britannia Industries Ltd.', 'asset_type': 'stocks', 'sector': 'Fast Moving Consumer Goods'},
    {'symbol': 'BSE', 'company_name': 'BSE Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'BSOFT', 'company_name': 'Birlasoft Ltd.', 'asset_type': 'stocks', 'sector': 'Information Technology'},
    {'symbol': 'CAMPUS', 'company_name': 'Campus Activewear Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Durables'},
    {'symbol': 'CAMS', 'company_name': 'Computer Age Management Services Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'CANBK', 'company_name': 'Canara Bank', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'CANFINHOME', 'company_name': 'Can Fin Homes Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'CAPLIPOINT', 'company_name': 'Caplin Point Laboratories Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'CARBORUNIV', 'company_name': 'Carborundum Universal Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'CASTROLIND', 'company_name': 'Castrol India Ltd.', 'asset_type': 'stocks', 'sector': 'Oil Gas & Consumable Fuels'},
    {'symbol': 'CCL', 'company_name': 'CCL Products (I) Ltd.', 'asset_type': 'stocks', 'sector': 'Fast Moving Consumer Goods'},
    {'symbol': 'CDSL', 'company_name': 'Central Depository Services (India) Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'CEATLTD', 'company_name': 'Ceat Ltd.', 'asset_type': 'stocks', 'sector': 'Automobile and Auto Components'},
    {'symbol': 'CENTRALBK', 'company_name': 'Central Bank of India', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'CENTURYPLY', 'company_name': 'Century Plyboards (India) Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Durables'},
    {'symbol': 'CERA', 'company_name': 'Cera Sanitaryware Ltd', 'asset_type': 'stocks', 'sector': 'Consumer Durables'},
    {'symbol': 'CESC', 'company_name': 'CESC Ltd.', 'asset_type': 'stocks', 'sector': 'Power'},
    {'symbol': 'CGCL', 'company_name': 'Capri Global Capital Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'CGPOWER', 'company_name': 'CG Power and Industrial Solutions Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'CHALET', 'company_name': 'Chalet Hotels Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Services'},
    {'symbol': 'CHAMBLFERT', 'company_name': 'Chambal Fertilizers & Chemicals Ltd.', 'asset_type': 'stocks', 'sector': 'Chemicals'},
    {'symbol': 'CHENNPETRO', 'company_name': 'Chennai Petroleum Corporation Ltd.', 'asset_type': 'stocks', 'sector': 'Oil Gas & Consumable Fuels'},
    {'symbol': 'CHOICEIN', 'company_name': 'Choice International Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'CHOLAFIN', 'company_name': 'Cholamandalam Investment and Finance Company Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'CHOLAHLDNG', 'company_name': 'Cholamandalam Financial Holdings Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'CIPLA', 'company_name': 'Cipla Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'CLEAN', 'company_name': 'Clean Science and Technology Ltd.', 'asset_type': 'stocks', 'sector': 'Chemicals'},
    {'symbol': 'COALINDIA', 'company_name': 'Coal India Ltd.', 'asset_type': 'stocks', 'sector': 'Oil Gas & Consumable Fuels'},
    {'symbol': 'COCHINSHIP', 'company_name': 'Cochin Shipyard Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'COFORGE', 'company_name': 'Coforge Ltd.', 'asset_type': 'stocks', 'sector': 'Information Technology'},
    {'symbol': 'COHANCE', 'company_name': 'Cohance Lifesciences Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'COLPAL', 'company_name': 'Colgate Palmolive (India) Ltd.', 'asset_type': 'stocks', 'sector': 'Fast Moving Consumer Goods'},
    {'symbol': 'CONCOR', 'company_name': 'Container Corporation of India Ltd.', 'asset_type': 'stocks', 'sector': 'Services'},
    {'symbol': 'CONCORDBIO', 'company_name': 'Concord Biotech Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'COROMANDEL', 'company_name': 'Coromandel International Ltd.', 'asset_type': 'stocks', 'sector': 'Chemicals'},
    {'symbol': 'CRAFTSMAN', 'company_name': 'Craftsman Automation Ltd.', 'asset_type': 'stocks', 'sector': 'Automobile and Auto Components'},
    {'symbol': 'CREDITACC', 'company_name': 'CreditAccess Grameen Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'CRISIL', 'company_name': 'CRISIL Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'CROMPTON', 'company_name': 'Crompton Greaves Consumer Electricals Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Durables'},
    {'symbol': 'CUB', 'company_name': 'City Union Bank Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'CUMMINSIND', 'company_name': 'Cummins India Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'CYIENT', 'company_name': 'Cyient Ltd.', 'asset_type': 'stocks', 'sector': 'Information Technology'},
    {'symbol': 'DABUR', 'company_name': 'Dabur India Ltd.', 'asset_type': 'stocks', 'sector': 'Fast Moving Consumer Goods'},
    {'symbol': 'DALBHARAT', 'company_name': 'Dalmia Bharat Ltd.', 'asset_type': 'stocks', 'sector': 'Construction Materials'},
    {'symbol': 'DATAPATTNS', 'company_name': 'Data Patterns (India) Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'DBREALTY', 'company_name': 'Valor Estate Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Services'},
    {'symbol': 'DCMSHRIRAM', 'company_name': 'DCM Shriram Ltd.', 'asset_type': 'stocks', 'sector': 'Diversified'},
    {'symbol': 'DEEPAKFERT', 'company_name': 'Deepak Fertilisers & Petrochemicals Corp. Ltd.', 'asset_type': 'stocks', 'sector': 'Chemicals'},
    {'symbol': 'DEEPAKNTR', 'company_name': 'Deepak Nitrite Ltd.', 'asset_type': 'stocks', 'sector': 'Chemicals'},
    {'symbol': 'DELHIVERY', 'company_name': 'Delhivery Ltd.', 'asset_type': 'stocks', 'sector': 'Services'},
    {'symbol': 'DEVYANI', 'company_name': 'Devyani International Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Services'},
    {'symbol': 'DIVISLAB', 'company_name': "Divi's Laboratories Ltd.", 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'DIXON', 'company_name': 'Dixon Technologies (India) Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Durables'},
    {'symbol': 'DLF', 'company_name': 'DLF Ltd.', 'asset_type': 'stocks', 'sector': 'Realty'},
    {'symbol': 'DMART', 'company_name': 'Avenue Supermarts Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Services'},
    {'symbol': 'DOMS', 'company_name': 'DOMS Industries Ltd.', 'asset_type': 'stocks', 'sector': 'Fast Moving Consumer Goods'},
    {'symbol': 'DRREDDY', 'company_name': "Dr. Reddy's Laboratories Ltd.", 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'DUMMYHDLVR', 'company_name': 'Dummy Hindustan Unilever Ltd.', 'asset_type': 'stocks', 'sector': 'Fast Moving Consumer Goods'},
    {'symbol': 'ECLERX', 'company_name': 'eClerx Services Ltd.', 'asset_type': 'stocks', 'sector': 'Services'},
    {'symbol': 'EICHERMOT', 'company_name': 'Eicher Motors Ltd.', 'asset_type': 'stocks', 'sector': 'Automobile and Auto Components'},
    {'symbol': 'EIDPARRY', 'company_name': 'E.I.D. Parry (India) Ltd.', 'asset_type': 'stocks', 'sector': 'Fast Moving Consumer Goods'},
    {'symbol': 'EIHOTEL', 'company_name': 'EIH Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Services'},
    {'symbol': 'ELECON', 'company_name': 'Elecon Engineering Co. Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'ELGIEQUIP', 'company_name': 'Elgi Equipments Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'EMAMILTD', 'company_name': 'Emami Ltd.', 'asset_type': 'stocks', 'sector': 'Fast Moving Consumer Goods'},
    {'symbol': 'EMCURE', 'company_name': 'Emcure Pharmaceuticals Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'ENDURANCE', 'company_name': 'Endurance Technologies Ltd.', 'asset_type': 'stocks', 'sector': 'Automobile and Auto Components'},
    {'symbol': 'ENGINERSIN', 'company_name': 'Engineers India Ltd.', 'asset_type': 'stocks', 'sector': 'Construction'},
    {'symbol': 'ENRIN', 'company_name': 'Siemens Energy India Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'ERIS', 'company_name': 'Eris Lifesciences Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'ESCORTS', 'company_name': 'Escorts Kubota Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'ETERNAL', 'company_name': 'Eternal Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Services'},
    {'symbol': 'EXIDEIND', 'company_name': 'Exide Industries Ltd.', 'asset_type': 'stocks', 'sector': 'Automobile and Auto Components'},
    {'symbol': 'FACT', 'company_name': 'Fertilisers and Chemicals Travancore Ltd.', 'asset_type': 'stocks', 'sector': 'Chemicals'},
    {'symbol': 'FEDERALBNK', 'company_name': 'Federal Bank Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'FINCABLES', 'company_name': 'Finolex Cables Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'FINPIPE', 'company_name': 'Finolex Industries Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'FIRSTCRY', 'company_name': 'Brainbees Solutions Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Services'},
    {'symbol': 'FIVESTAR', 'company_name': 'Five-Star Business Finance Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'FLUOROCHEM', 'company_name': 'Gujarat Fluorochemicals Ltd.', 'asset_type': 'stocks', 'sector': 'Chemicals'},
    {'symbol': 'FORCEMOT', 'company_name': 'Force Motors Ltd.', 'asset_type': 'stocks', 'sector': 'Automobile and Auto Components'},
    {'symbol': 'FORTIS', 'company_name': 'Fortis Healthcare Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'FSL', 'company_name': 'Firstsource Solutions Ltd.', 'asset_type': 'stocks', 'sector': 'Services'},
    {'symbol': 'GAIL', 'company_name': 'GAIL (India) Ltd.', 'asset_type': 'stocks', 'sector': 'Oil Gas & Consumable Fuels'},
    {'symbol': 'GESHIP', 'company_name': 'Great Eastern Shipping Co. Ltd.', 'asset_type': 'stocks', 'sector': 'Services'},
    {'symbol': 'GICRE', 'company_name': 'General Insurance Corporation of India', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'GILLETTE', 'company_name': 'Gillette India Ltd.', 'asset_type': 'stocks', 'sector': 'Fast Moving Consumer Goods'},
    {'symbol': 'GLAND', 'company_name': 'Gland Pharma Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'GLAXO', 'company_name': 'Glaxosmithkline Pharmaceuticals Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'GLENMARK', 'company_name': 'Glenmark Pharmaceuticals Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'GMDCLTD', 'company_name': 'Gujarat Mineral Development Corporation Ltd.', 'asset_type': 'stocks', 'sector': 'Metals & Mining'},
    {'symbol': 'GMRAIRPORT', 'company_name': 'GMR Airports Ltd.', 'asset_type': 'stocks', 'sector': 'Services'},
    {'symbol': 'GODFRYPHLP', 'company_name': 'Godfrey Phillips India Ltd.', 'asset_type': 'stocks', 'sector': 'Fast Moving Consumer Goods'},
    {'symbol': 'GODIGIT', 'company_name': 'Go Digit General Insurance Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'GODREJAGRO', 'company_name': 'Godrej Agrovet Ltd.', 'asset_type': 'stocks', 'sector': 'Fast Moving Consumer Goods'},
    {'symbol': 'GODREJCP', 'company_name': 'Godrej Consumer Products Ltd.', 'asset_type': 'stocks', 'sector': 'Fast Moving Consumer Goods'},
    {'symbol': 'GODREJIND', 'company_name': 'Godrej Industries Ltd.', 'asset_type': 'stocks', 'sector': 'Diversified'},
    {'symbol': 'GODREJPROP', 'company_name': 'Godrej Properties Ltd.', 'asset_type': 'stocks', 'sector': 'Realty'},
    {'symbol': 'GPIL', 'company_name': 'Godawari Power & Ispat Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'GRANULES', 'company_name': 'Granules India Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'GRAPHITE', 'company_name': 'Graphite India Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'GRASIM', 'company_name': 'Grasim Industries Ltd.', 'asset_type': 'stocks', 'sector': 'Construction Materials'},
    {'symbol': 'GRAVITA', 'company_name': 'Gravita India Ltd.', 'asset_type': 'stocks', 'sector': 'Metals & Mining'},
    {'symbol': 'GRSE', 'company_name': 'Garden Reach Shipbuilders & Engineers Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'GSPL', 'company_name': 'Gujarat State Petronet Ltd.', 'asset_type': 'stocks', 'sector': 'Oil Gas & Consumable Fuels'},
    {'symbol': 'GUJGASLTD', 'company_name': 'Gujarat Gas Ltd.', 'asset_type': 'stocks', 'sector': 'Oil Gas & Consumable Fuels'},
    {'symbol': 'GVT&D', 'company_name': 'GE Vernova T&D India Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'HAL', 'company_name': 'Hindustan Aeronautics Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'HAPPSTMNDS', 'company_name': 'Happiest Minds Technologies Ltd.', 'asset_type': 'stocks', 'sector': 'Information Technology'},
    {'symbol': 'HAVELLS', 'company_name': 'Havells India Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Durables'},
    {'symbol': 'HBLENGINE', 'company_name': 'HBL Engineering Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'HCLTECH', 'company_name': 'HCL Technologies Ltd.', 'asset_type': 'stocks', 'sector': 'Information Technology'},
    {'symbol': 'HDFCAMC', 'company_name': 'HDFC Asset Management Company Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'HDFCBANK', 'company_name': 'HDFC Bank Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'HDFCLIFE', 'company_name': 'HDFC Life Insurance Company Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'HEG', 'company_name': 'H.E.G. Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'HEROMOTOCO', 'company_name': 'Hero MotoCorp Ltd.', 'asset_type': 'stocks', 'sector': 'Automobile and Auto Components'},
    {'symbol': 'HEXT', 'company_name': 'Hexaware Technologies Ltd.', 'asset_type': 'stocks', 'sector': 'Information Technology'},
    {'symbol': 'HFCL', 'company_name': 'HFCL Ltd.', 'asset_type': 'stocks', 'sector': 'Telecommunication'},
    {'symbol': 'HINDALCO', 'company_name': 'Hindalco Industries Ltd.', 'asset_type': 'stocks', 'sector': 'Metals & Mining'},
    {'symbol': 'HINDCOPPER', 'company_name': 'Hindustan Copper Ltd.', 'asset_type': 'stocks', 'sector': 'Metals & Mining'},
    {'symbol': 'HINDPETRO', 'company_name': 'Hindustan Petroleum Corporation Ltd.', 'asset_type': 'stocks', 'sector': 'Oil Gas & Consumable Fuels'},
    {'symbol': 'HINDUNILVR', 'company_name': 'Hindustan Unilever Ltd.', 'asset_type': 'stocks', 'sector': 'Fast Moving Consumer Goods'},
    {'symbol': 'HINDZINC', 'company_name': 'Hindustan Zinc Ltd.', 'asset_type': 'stocks', 'sector': 'Metals & Mining'},
    {'symbol': 'HOMEFIRST', 'company_name': 'Home First Finance Company India Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'HONASA', 'company_name': 'Honasa Consumer Ltd.', 'asset_type': 'stocks', 'sector': 'Fast Moving Consumer Goods'},
    {'symbol': 'HONAUT', 'company_name': 'Honeywell Automation India Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'HSCL', 'company_name': 'Himadri Speciality Chemical Ltd.', 'asset_type': 'stocks', 'sector': 'Chemicals'},
    {'symbol': 'HUDCO', 'company_name': 'Housing & Urban Development Corporation Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'HYUNDAI', 'company_name': 'Hyundai Motor India Ltd.', 'asset_type': 'stocks', 'sector': 'Automobile and Auto Components'},
    {'symbol': 'ICICIBANK', 'company_name': 'ICICI Bank Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'ICICIGI', 'company_name': 'ICICI Lombard General Insurance Company Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'ICICIPRULI', 'company_name': 'ICICI Prudential Life Insurance Company Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'IDBI', 'company_name': 'IDBI Bank Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'IDEA', 'company_name': 'Vodafone Idea Ltd.', 'asset_type': 'stocks', 'sector': 'Telecommunication'},
    {'symbol': 'IDFCFIRSTB', 'company_name': 'IDFC First Bank Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'IEX', 'company_name': 'Indian Energy Exchange Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'IFCI', 'company_name': 'IFCI Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'IGIL', 'company_name': 'International Gemmological Institute (India) Ltd.', 'asset_type': 'stocks', 'sector': 'Services'},
    {'symbol': 'IGL', 'company_name': 'Indraprastha Gas Ltd.', 'asset_type': 'stocks', 'sector': 'Oil Gas & Consumable Fuels'},
    {'symbol': 'IIFL', 'company_name': 'IIFL Finance Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'IKS', 'company_name': 'Inventurus Knowledge Solutions Ltd.', 'asset_type': 'stocks', 'sector': 'Information Technology'},
    {'symbol': 'INDGN', 'company_name': 'Indegene Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'INDHOTEL', 'company_name': 'Indian Hotels Co. Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Services'},
    {'symbol': 'INDIACEM', 'company_name': 'India Cements Ltd.', 'asset_type': 'stocks', 'sector': 'Construction Materials'},
    {'symbol': 'INDIAMART', 'company_name': 'Indiamart Intermesh Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Services'},
    {'symbol': 'INDIANB', 'company_name': 'Indian Bank', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'INDIGO', 'company_name': 'InterGlobe Aviation Ltd.', 'asset_type': 'stocks', 'sector': 'Services'},
    {'symbol': 'INDUSINDBK', 'company_name': 'IndusInd Bank Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'INDUSTOWER', 'company_name': 'Indus Towers Ltd.', 'asset_type': 'stocks', 'sector': 'Telecommunication'},
    {'symbol': 'INFY', 'company_name': 'Infosys Ltd.', 'asset_type': 'stocks', 'sector': 'Information Technology'},
    {'symbol': 'INOXINDIA', 'company_name': 'INOX India Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'INOXWIND', 'company_name': 'Inox Wind Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'INTELLECT', 'company_name': 'Intellect Design Arena Ltd.', 'asset_type': 'stocks', 'sector': 'Information Technology'},
    {'symbol': 'IOB', 'company_name': 'Indian Overseas Bank', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'IOC', 'company_name': 'Indian Oil Corporation Ltd.', 'asset_type': 'stocks', 'sector': 'Oil Gas & Consumable Fuels'},
    {'symbol': 'IPCALAB', 'company_name': 'Ipca Laboratories Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'IRB', 'company_name': 'IRB Infrastructure Developers Ltd.', 'asset_type': 'stocks', 'sector': 'Construction'},
    {'symbol': 'IRCON', 'company_name': 'IRCON International Ltd.', 'asset_type': 'stocks', 'sector': 'Construction'},
    {'symbol': 'IRCTC', 'company_name': 'Indian Railway Catering And Tourism Corporation Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Services'},
    {'symbol': 'IREDA', 'company_name': 'Indian Renewable Energy Development Agency Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'IRFC', 'company_name': 'Indian Railway Finance Corporation Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'ITC', 'company_name': 'ITC Ltd.', 'asset_type': 'stocks', 'sector': 'Fast Moving Consumer Goods'},
    {'symbol': 'ITCHOTELS', 'company_name': 'ITC Hotels Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Services'},
    {'symbol': 'ITI', 'company_name': 'ITI Ltd.', 'asset_type': 'stocks', 'sector': 'Telecommunication'},
    {'symbol': 'J&KBANK', 'company_name': 'Jammu & Kashmir Bank Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'JBCHEPHARM', 'company_name': 'J.B. Chemicals & Pharmaceuticals Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'JBMA', 'company_name': 'JBM Auto Ltd.', 'asset_type': 'stocks', 'sector': 'Automobile and Auto Components'},
    {'symbol': 'JINDALSAW', 'company_name': 'Jindal Saw Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'JINDALSTEL', 'company_name': 'Jindal Steel Ltd.', 'asset_type': 'stocks', 'sector': 'Metals & Mining'},
    {'symbol': 'JIOFIN', 'company_name': 'Jio Financial Services Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'JKCEMENT', 'company_name': 'J.K. Cement Ltd.', 'asset_type': 'stocks', 'sector': 'Construction Materials'},
    {'symbol': 'JKTYRE', 'company_name': 'JK Tyre & Industries Ltd.', 'asset_type': 'stocks', 'sector': 'Automobile and Auto Components'},
    {'symbol': 'JMFINANCIL', 'company_name': 'JM Financial Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'JPPOWER', 'company_name': 'Jaiprakash Power Ventures Ltd.', 'asset_type': 'stocks', 'sector': 'Power'},
    {'symbol': 'JSL', 'company_name': 'Jindal Stainless Ltd.', 'asset_type': 'stocks', 'sector': 'Metals & Mining'},
    {'symbol': 'JSWCEMENT', 'company_name': 'JSW Cement Ltd.', 'asset_type': 'stocks', 'sector': 'Construction Materials'},
    {'symbol': 'JSWENERGY', 'company_name': 'JSW Energy Ltd.', 'asset_type': 'stocks', 'sector': 'Power'},
    {'symbol': 'JSWINFRA', 'company_name': 'JSW Infrastructure Ltd.', 'asset_type': 'stocks', 'sector': 'Services'},
    {'symbol': 'JSWSTEEL', 'company_name': 'JSW Steel Ltd.', 'asset_type': 'stocks', 'sector': 'Metals & Mining'},
    {'symbol': 'JUBLFOOD', 'company_name': 'Jubilant Foodworks Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Services'},
    {'symbol': 'JUBLINGREA', 'company_name': 'Jubilant Ingrevia Ltd.', 'asset_type': 'stocks', 'sector': 'Chemicals'},
    {'symbol': 'JUBLPHARMA', 'company_name': 'Jubilant Pharmova Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'JWL', 'company_name': 'Jupiter Wagons Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'JYOTHYLAB', 'company_name': 'Jyothy Labs Ltd.', 'asset_type': 'stocks', 'sector': 'Fast Moving Consumer Goods'},
    {'symbol': 'JYOTICNC', 'company_name': 'Jyoti CNC Automation Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'KAJARIACER', 'company_name': 'Kajaria Ceramics Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Durables'},
    {'symbol': 'KALYANKJIL', 'company_name': 'Kalyan Jewellers India Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Durables'},
    {'symbol': 'KARURVYSYA', 'company_name': 'Karur Vysya Bank Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'KAYNES', 'company_name': 'Kaynes Technology India Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'KEC', 'company_name': 'Kec International Ltd.', 'asset_type': 'stocks', 'sector': 'Construction'},
    {'symbol': 'KEI', 'company_name': 'KEI Industries Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'KFINTECH', 'company_name': 'Kfin Technologies Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'KIMS', 'company_name': 'Krishna Institute of Medical Sciences Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'KIRLOSBROS', 'company_name': 'Kirloskar Brothers Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'KIRLOSENG', 'company_name': 'Kirloskar Oil Eng Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'KOTAKBANK', 'company_name': 'Kotak Mahindra Bank Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'KPIL', 'company_name': 'Kalpataru Projects International Ltd.', 'asset_type': 'stocks', 'sector': 'Construction'},
    {'symbol': 'KPITTECH', 'company_name': 'KPIT Technologies Ltd.', 'asset_type': 'stocks', 'sector': 'Information Technology'},
    {'symbol': 'KPRMILL', 'company_name': 'K.P.R. Mill Ltd.', 'asset_type': 'stocks', 'sector': 'Textiles'},
    {'symbol': 'KSB', 'company_name': 'KSB Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'LALPATHLAB', 'company_name': 'Dr. Lal Path Labs Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'LATENTVIEW', 'company_name': 'Latent View Analytics Ltd.', 'asset_type': 'stocks', 'sector': 'Information Technology'},
    {'symbol': 'LAURUSLABS', 'company_name': 'Laurus Labs Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'LEMONTREE', 'company_name': 'Lemon Tree Hotels Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Services'},
    {'symbol': 'LICHSGFIN', 'company_name': 'LIC Housing Finance Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'LICI', 'company_name': 'Life Insurance Corporation of India', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'LINDEINDIA', 'company_name': 'Linde India Ltd.', 'asset_type': 'stocks', 'sector': 'Chemicals'},
    {'symbol': 'LLOYDSME', 'company_name': 'Lloyds Metals And Energy Ltd.', 'asset_type': 'stocks', 'sector': 'Metals & Mining'},
    {'symbol': 'LODHA', 'company_name': 'Lodha Developers Ltd.', 'asset_type': 'stocks', 'sector': 'Realty'},
    {'symbol': 'LT', 'company_name': 'Larsen & Toubro Ltd.', 'asset_type': 'stocks', 'sector': 'Construction'},
    {'symbol': 'LTF', 'company_name': 'L&T Finance Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'LTFOODS', 'company_name': 'LT Foods Ltd.', 'asset_type': 'stocks', 'sector': 'Fast Moving Consumer Goods'},
    {'symbol': 'LTIM', 'company_name': 'LTIMindtree Ltd.', 'asset_type': 'stocks', 'sector': 'Information Technology'},
    {'symbol': 'LTTS', 'company_name': 'L&T Technology Services Ltd.', 'asset_type': 'stocks', 'sector': 'Information Technology'},
    {'symbol': 'LUPIN', 'company_name': 'Lupin Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'M&M', 'company_name': 'Mahindra & Mahindra Ltd.', 'asset_type': 'stocks', 'sector': 'Automobile and Auto Components'},
    {'symbol': 'M&MFIN', 'company_name': 'Mahindra & Mahindra Financial Services Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'MAHABANK', 'company_name': 'Bank of Maharashtra', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'MAHSCOOTER', 'company_name': 'Maharashtra Scooters Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'MAHSEAMLES', 'company_name': 'Maharashtra Seamless Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'MANAPPURAM', 'company_name': 'Manappuram Finance Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'MANKIND', 'company_name': 'Mankind Pharma Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'MANYAVAR', 'company_name': 'Vedant Fashions Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Services'},
    {'symbol': 'MAPMYINDIA', 'company_name': 'C.E. Info Systems Ltd.', 'asset_type': 'stocks', 'sector': 'Information Technology'},
    {'symbol': 'MARICO', 'company_name': 'Marico Ltd.', 'asset_type': 'stocks', 'sector': 'Fast Moving Consumer Goods'},
    {'symbol': 'MARUTI', 'company_name': 'Maruti Suzuki India Ltd.', 'asset_type': 'stocks', 'sector': 'Automobile and Auto Components'},
    {'symbol': 'MAXHEALTH', 'company_name': 'Max Healthcare Institute Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'MAZDOCK', 'company_name': 'Mazagoan Dock Shipbuilders Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'MCX', 'company_name': 'Multi Commodity Exchange of India Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'MEDANTA', 'company_name': 'Global Health Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'METROPOLIS', 'company_name': 'Metropolis Healthcare Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'MFSL', 'company_name': 'Max Financial Services Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'MGL', 'company_name': 'Mahanagar Gas Ltd.', 'asset_type': 'stocks', 'sector': 'Oil Gas & Consumable Fuels'},
    {'symbol': 'MINDACORP', 'company_name': 'Minda Corporation Ltd.', 'asset_type': 'stocks', 'sector': 'Automobile and Auto Components'},
    {'symbol': 'MMTC', 'company_name': 'MMTC Ltd.', 'asset_type': 'stocks', 'sector': 'Services'},
    {'symbol': 'MOTHERSON', 'company_name': 'Samvardhana Motherson International Ltd.', 'asset_type': 'stocks', 'sector': 'Automobile and Auto Components'},
    {'symbol': 'MOTILALOFS', 'company_name': 'Motilal Oswal Financial Services Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'MPHASIS', 'company_name': 'MphasiS Ltd.', 'asset_type': 'stocks', 'sector': 'Information Technology'},
    {'symbol': 'MRF', 'company_name': 'MRF Ltd.', 'asset_type': 'stocks', 'sector': 'Automobile and Auto Components'},
    {'symbol': 'MRPL', 'company_name': 'Mangalore Refinery & Petrochemicals Ltd.', 'asset_type': 'stocks', 'sector': 'Oil Gas & Consumable Fuels'},
    {'symbol': 'MSUMI', 'company_name': 'Motherson Sumi Wiring India Ltd.', 'asset_type': 'stocks', 'sector': 'Automobile and Auto Components'},
    {'symbol': 'MUTHOOTFIN', 'company_name': 'Muthoot Finance Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'NAM-INDIA', 'company_name': 'Nippon Life India Asset Management Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'NATCOPHARM', 'company_name': 'NATCO Pharma Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'NATIONALUM', 'company_name': 'National Aluminium Co. Ltd.', 'asset_type': 'stocks', 'sector': 'Metals & Mining'},
    {'symbol': 'NAUKRI', 'company_name': 'Info Edge (India) Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Services'},
    {'symbol': 'NAVA', 'company_name': 'Nava Ltd.', 'asset_type': 'stocks', 'sector': 'Power'},
    {'symbol': 'NAVINFLUOR', 'company_name': 'Navin Fluorine International Ltd.', 'asset_type': 'stocks', 'sector': 'Chemicals'},
    {'symbol': 'NBCC', 'company_name': 'NBCC (India) Ltd.', 'asset_type': 'stocks', 'sector': 'Construction'},
    {'symbol': 'NCC', 'company_name': 'NCC Ltd.', 'asset_type': 'stocks', 'sector': 'Construction'},
    {'symbol': 'NESTLEIND', 'company_name': 'Nestle India Ltd.', 'asset_type': 'stocks', 'sector': 'Fast Moving Consumer Goods'},
    {'symbol': 'NETWEB', 'company_name': 'Netweb Technologies India Ltd.', 'asset_type': 'stocks', 'sector': 'Information Technology'},
    {'symbol': 'NEULANDLAB', 'company_name': 'Neuland Laboratories Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'NEWGEN', 'company_name': 'Newgen Software Technologies Ltd.', 'asset_type': 'stocks', 'sector': 'Information Technology'},
    {'symbol': 'NH', 'company_name': 'Narayana Hrudayalaya Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'NHPC', 'company_name': 'NHPC Ltd.', 'asset_type': 'stocks', 'sector': 'Power'},
    {'symbol': 'NIACL', 'company_name': 'The New India Assurance Company Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'NIVABUPA', 'company_name': 'Niva Bupa Health Insurance Company Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'NLCINDIA', 'company_name': 'NLC India Ltd.', 'asset_type': 'stocks', 'sector': 'Power'},
    {'symbol': 'NMDC', 'company_name': 'NMDC Ltd.', 'asset_type': 'stocks', 'sector': 'Metals & Mining'},
    {'symbol': 'NSLNISP', 'company_name': 'NMDC Steel Ltd.', 'asset_type': 'stocks', 'sector': 'Metals & Mining'},
    {'symbol': 'NTPC', 'company_name': 'NTPC Ltd.', 'asset_type': 'stocks', 'sector': 'Power'},
    {'symbol': 'NTPCGREEN', 'company_name': 'NTPC Green Energy Ltd.', 'asset_type': 'stocks', 'sector': 'Power'},
    {'symbol': 'NUVAMA', 'company_name': 'Nuvama Wealth Management Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'NUVOCO', 'company_name': 'Nuvoco Vistas Corporation Ltd.', 'asset_type': 'stocks', 'sector': 'Construction Materials'},
    {'symbol': 'NYKAA', 'company_name': 'FSN E-Commerce Ventures Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Services'},
    {'symbol': 'OBEROIRLTY', 'company_name': 'Oberoi Realty Ltd.', 'asset_type': 'stocks', 'sector': 'Realty'},
    {'symbol': 'OFSS', 'company_name': 'Oracle Financial Services Software Ltd.', 'asset_type': 'stocks', 'sector': 'Information Technology'},
    {'symbol': 'OIL', 'company_name': 'Oil India Ltd.', 'asset_type': 'stocks', 'sector': 'Oil Gas & Consumable Fuels'},
    {'symbol': 'OLAELEC', 'company_name': 'Ola Electric Mobility Ltd.', 'asset_type': 'stocks', 'sector': 'Automobile and Auto Components'},
    {'symbol': 'OLECTRA', 'company_name': 'Olectra Greentech Ltd.', 'asset_type': 'stocks', 'sector': 'Automobile and Auto Components'},
    {'symbol': 'ONESOURCE', 'company_name': 'Onesource Specialty Pharma Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'ONGC', 'company_name': 'Oil & Natural Gas Corporation Ltd.', 'asset_type': 'stocks', 'sector': 'Oil Gas & Consumable Fuels'},
    {'symbol': 'PAGEIND', 'company_name': 'Page Industries Ltd.', 'asset_type': 'stocks', 'sector': 'Textiles'},
    {'symbol': 'PATANJALI', 'company_name': 'Patanjali Foods Ltd.', 'asset_type': 'stocks', 'sector': 'Fast Moving Consumer Goods'},
    {'symbol': 'PAYTM', 'company_name': 'One 97 Communications Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'PCBL', 'company_name': 'PCBL Chemical Ltd.', 'asset_type': 'stocks', 'sector': 'Chemicals'},
    {'symbol': 'PERSISTENT', 'company_name': 'Persistent Systems Ltd.', 'asset_type': 'stocks', 'sector': 'Information Technology'},
    {'symbol': 'PETRONET', 'company_name': 'Petronet LNG Ltd.', 'asset_type': 'stocks', 'sector': 'Oil Gas & Consumable Fuels'},
    {'symbol': 'PFC', 'company_name': 'Power Finance Corporation Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'PFIZER', 'company_name': 'Pfizer Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'PGEL', 'company_name': 'PG Electroplast Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Durables'},
    {'symbol': 'PGHH', 'company_name': 'Procter & Gamble Hygiene & Health Care Ltd.', 'asset_type': 'stocks', 'sector': 'Fast Moving Consumer Goods'},
    {'symbol': 'PHOENIXLTD', 'company_name': 'Phoenix Mills Ltd.', 'asset_type': 'stocks', 'sector': 'Realty'},
    {'symbol': 'PIDILITIND', 'company_name': 'Pidilite Industries Ltd.', 'asset_type': 'stocks', 'sector': 'Chemicals'},
    {'symbol': 'PIIND', 'company_name': 'PI Industries Ltd.', 'asset_type': 'stocks', 'sector': 'Chemicals'},
    {'symbol': 'PNB', 'company_name': 'Punjab National Bank', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'PNBHOUSING', 'company_name': 'PNB Housing Finance Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'POLICYBZR', 'company_name': 'PB Fintech Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'POLYCAB', 'company_name': 'Polycab India Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'POLYMED', 'company_name': 'Poly Medicure Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'POONAWALLA', 'company_name': 'Poonawalla Fincorp Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'POWERGRID', 'company_name': 'Power Grid Corporation of India Ltd.', 'asset_type': 'stocks', 'sector': 'Power'},
    {'symbol': 'POWERINDIA', 'company_name': 'Hitachi Energy India Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'PPLPHARMA', 'company_name': 'Piramal Pharma Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'PRAJIND', 'company_name': 'Praj Industries Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'PREMIERENE', 'company_name': 'Premier Energies Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'PRESTIGE', 'company_name': 'Prestige Estates Projects Ltd.', 'asset_type': 'stocks', 'sector': 'Realty'},
    {'symbol': 'PTCIL', 'company_name': 'PTC Industries Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'PVRINOX', 'company_name': 'PVR INOX Ltd.', 'asset_type': 'stocks', 'sector': 'Media Entertainment & Publication'},
    {'symbol': 'RADICO', 'company_name': 'Radico Khaitan Ltd', 'asset_type': 'stocks', 'sector': 'Fast Moving Consumer Goods'},
    {'symbol': 'RAILTEL', 'company_name': 'Railtel Corporation Of India Ltd.', 'asset_type': 'stocks', 'sector': 'Telecommunication'},
    {'symbol': 'RAINBOW', 'company_name': 'Rainbow Childrens Medicare Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'RAMCOCEM', 'company_name': 'The Ramco Cements Ltd.', 'asset_type': 'stocks', 'sector': 'Construction Materials'},
    {'symbol': 'RBLBANK', 'company_name': 'RBL Bank Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'RCF', 'company_name': 'Rashtriya Chemicals & Fertilizers Ltd.', 'asset_type': 'stocks', 'sector': 'Chemicals'},
    {'symbol': 'RECLTD', 'company_name': 'REC Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'REDINGTON', 'company_name': 'Redington Ltd.', 'asset_type': 'stocks', 'sector': 'Services'},
    {'symbol': 'RELIANCE', 'company_name': 'Reliance Industries Ltd.', 'asset_type': 'stocks', 'sector': 'Oil Gas & Consumable Fuels'},
    {'symbol': 'RELINFRA', 'company_name': 'Reliance Infrastructure Ltd.', 'asset_type': 'stocks', 'sector': 'Power'},
    {'symbol': 'RHIM', 'company_name': 'RHI MAGNESITA INDIA LTD.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'RITES', 'company_name': 'RITES Ltd.', 'asset_type': 'stocks', 'sector': 'Construction'},
    {'symbol': 'RKFORGE', 'company_name': 'Ramkrishna Forgings Ltd.', 'asset_type': 'stocks', 'sector': 'Automobile and Auto Components'},
    {'symbol': 'RPOWER', 'company_name': 'Reliance Power Ltd.', 'asset_type': 'stocks', 'sector': 'Power'},
    {'symbol': 'RRKABEL', 'company_name': 'R R Kabel Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'RVNL', 'company_name': 'Rail Vikas Nigam Ltd.', 'asset_type': 'stocks', 'sector': 'Construction'},
    {'symbol': 'SAGILITY', 'company_name': 'Sagility Ltd.', 'asset_type': 'stocks', 'sector': 'Information Technology'},
    {'symbol': 'SAIL', 'company_name': 'Steel Authority of India Ltd.', 'asset_type': 'stocks', 'sector': 'Metals & Mining'},
    {'symbol': 'SAILIFE', 'company_name': 'Sai Life Sciences Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'SAMMAANCAP', 'company_name': 'Sammaan Capital Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'SAPPHIRE', 'company_name': 'Sapphire Foods India Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Services'},
    {'symbol': 'SARDAEN', 'company_name': 'Sarda Energy and Minerals Ltd.', 'asset_type': 'stocks', 'sector': 'Metals & Mining'},
    {'symbol': 'SAREGAMA', 'company_name': 'Saregama India Ltd', 'asset_type': 'stocks', 'sector': 'Media Entertainment & Publication'},
    {'symbol': 'SBFC', 'company_name': 'SBFC Finance Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'SBICARD', 'company_name': 'SBI Cards and Payment Services Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'SBILIFE', 'company_name': 'SBI Life Insurance Company Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'SBIN', 'company_name': 'State Bank of India', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'SCHAEFFLER', 'company_name': 'Schaeffler India Ltd.', 'asset_type': 'stocks', 'sector': 'Automobile and Auto Components'},
    {'symbol': 'SCHNEIDER', 'company_name': 'Schneider Electric Infrastructure Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'SCI', 'company_name': 'Shipping Corporation of India Ltd.', 'asset_type': 'stocks', 'sector': 'Services'},
    {'symbol': 'SHREECEM', 'company_name': 'Shree Cement Ltd.', 'asset_type': 'stocks', 'sector': 'Construction Materials'},
    {'symbol': 'SHRIRAMFIN', 'company_name': 'Shriram Finance Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'SHYAMMETL', 'company_name': 'Shyam Metalics and Energy Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'SIEMENS', 'company_name': 'Siemens Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'SIGNATURE', 'company_name': 'Signatureglobal (India) Ltd.', 'asset_type': 'stocks', 'sector': 'Realty'},
    {'symbol': 'SJVN', 'company_name': 'SJVN Ltd.', 'asset_type': 'stocks', 'sector': 'Power'},
    {'symbol': 'SOBHA', 'company_name': 'Sobha Ltd.', 'asset_type': 'stocks', 'sector': 'Realty'},
    {'symbol': 'SOLARINDS', 'company_name': 'Solar Industries India Ltd.', 'asset_type': 'stocks', 'sector': 'Chemicals'},
    {'symbol': 'SONACOMS', 'company_name': 'Sona BLW Precision Forgings Ltd.', 'asset_type': 'stocks', 'sector': 'Automobile and Auto Components'},
    {'symbol': 'SONATSOFTW', 'company_name': 'Sonata Software Ltd.', 'asset_type': 'stocks', 'sector': 'Information Technology'},
    {'symbol': 'SRF', 'company_name': 'SRF Ltd.', 'asset_type': 'stocks', 'sector': 'Chemicals'},
    {'symbol': 'STARHEALTH', 'company_name': 'Star Health and Allied Insurance Company Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'SUMICHEM', 'company_name': 'Sumitomo Chemical India Ltd.', 'asset_type': 'stocks', 'sector': 'Chemicals'},
    {'symbol': 'SUNDARMFIN', 'company_name': 'Sundaram Finance Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'SUNDRMFAST', 'company_name': 'Sundram Fasteners Ltd.', 'asset_type': 'stocks', 'sector': 'Automobile and Auto Components'},
    {'symbol': 'SUNPHARMA', 'company_name': 'Sun Pharmaceutical Industries Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'SUNTV', 'company_name': 'Sun TV Network Ltd.', 'asset_type': 'stocks', 'sector': 'Media Entertainment & Publication'},
    {'symbol': 'SUPREMEIND', 'company_name': 'Supreme Industries Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'SUZLON', 'company_name': 'Suzlon Energy Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'SWANCORP', 'company_name': 'Swan Corp Ltd.', 'asset_type': 'stocks', 'sector': 'Chemicals'},
    {'symbol': 'SWIGGY', 'company_name': 'Swiggy Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Services'},
    {'symbol': 'SYNGENE', 'company_name': 'Syngene International Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'SYRMA', 'company_name': 'Syrma SGS Technology Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'TARIL', 'company_name': 'Transformers And Rectifiers (India) Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'TATACHEM', 'company_name': 'Tata Chemicals Ltd.', 'asset_type': 'stocks', 'sector': 'Chemicals'},
    {'symbol': 'TATACOMM', 'company_name': 'Tata Communications Ltd.', 'asset_type': 'stocks', 'sector': 'Telecommunication'},
    {'symbol': 'TATACONSUM', 'company_name': 'Tata Consumer Products Ltd.', 'asset_type': 'stocks', 'sector': 'Fast Moving Consumer Goods'},
    {'symbol': 'TATAELXSI', 'company_name': 'Tata Elxsi Ltd.', 'asset_type': 'stocks', 'sector': 'Information Technology'},
    {'symbol': 'TATAINVEST', 'company_name': 'Tata Investment Corporation Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'TATAPOWER', 'company_name': 'Tata Power Co. Ltd.', 'asset_type': 'stocks', 'sector': 'Power'},
    {'symbol': 'TATASTEEL', 'company_name': 'Tata Steel Ltd.', 'asset_type': 'stocks', 'sector': 'Metals & Mining'},
    {'symbol': 'TATATECH', 'company_name': 'Tata Technologies Ltd.', 'asset_type': 'stocks', 'sector': 'Information Technology'},
    {'symbol': 'TBOTEK', 'company_name': 'TBO Tek Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Services'},
    {'symbol': 'TCS', 'company_name': 'Tata Consultancy Services Ltd.', 'asset_type': 'stocks', 'sector': 'Information Technology'},
    {'symbol': 'TECHM', 'company_name': 'Tech Mahindra Ltd.', 'asset_type': 'stocks', 'sector': 'Information Technology'},
    {'symbol': 'TECHNOE', 'company_name': 'Techno Electric & Engineering Company Ltd.', 'asset_type': 'stocks', 'sector': 'Construction'},
    {'symbol': 'TEJASNET', 'company_name': 'Tejas Networks Ltd.', 'asset_type': 'stocks', 'sector': 'Telecommunication'},
    {'symbol': 'THELEELA', 'company_name': 'Leela Palaces Hotels & Resorts Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Services'},
    {'symbol': 'THERMAX', 'company_name': 'Thermax Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'TIINDIA', 'company_name': 'Tube Investments of India Ltd.', 'asset_type': 'stocks', 'sector': 'Automobile and Auto Components'},
    {'symbol': 'TIMKEN', 'company_name': 'Timken India Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'TITAGARH', 'company_name': 'Titagarh Rail Systems Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'TITAN', 'company_name': 'Titan Company Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Durables'},
    {'symbol': 'TMPV', 'company_name': 'Tata Motors Passenger Vehicles Ltd.', 'asset_type': 'stocks', 'sector': 'Automobile and Auto Components'},
    {'symbol': 'TORNTPHARM', 'company_name': 'Torrent Pharmaceuticals Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'TORNTPOWER', 'company_name': 'Torrent Power Ltd.', 'asset_type': 'stocks', 'sector': 'Power'},
    {'symbol': 'TRENT', 'company_name': 'Trent Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Services'},
    {'symbol': 'TRIDENT', 'company_name': 'Trident Ltd.', 'asset_type': 'stocks', 'sector': 'Textiles'},
    {'symbol': 'TRITURBINE', 'company_name': 'Triveni Turbine Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'TRIVENI', 'company_name': 'Triveni Engineering & Industries Ltd.', 'asset_type': 'stocks', 'sector': 'Fast Moving Consumer Goods'},
    {'symbol': 'TTML', 'company_name': 'Tata Teleservices (Maharashtra) Ltd.', 'asset_type': 'stocks', 'sector': 'Telecommunication'},
    {'symbol': 'TVSMOTOR', 'company_name': 'TVS Motor Company Ltd.', 'asset_type': 'stocks', 'sector': 'Automobile and Auto Components'},
    {'symbol': 'UBL', 'company_name': 'United Breweries Ltd.', 'asset_type': 'stocks', 'sector': 'Fast Moving Consumer Goods'},
    {'symbol': 'UCOBANK', 'company_name': 'UCO Bank', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'ULTRACEMCO', 'company_name': 'UltraTech Cement Ltd.', 'asset_type': 'stocks', 'sector': 'Construction Materials'},
    {'symbol': 'UNIONBANK', 'company_name': 'Union Bank of India', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'UNITDSPR', 'company_name': 'United Spirits Ltd.', 'asset_type': 'stocks', 'sector': 'Fast Moving Consumer Goods'},
    {'symbol': 'UNOMINDA', 'company_name': 'UNO Minda Ltd.', 'asset_type': 'stocks', 'sector': 'Automobile and Auto Components'},
    {'symbol': 'UPL', 'company_name': 'UPL Ltd.', 'asset_type': 'stocks', 'sector': 'Chemicals'},
    {'symbol': 'USHAMART', 'company_name': 'Usha Martin Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'UTIAMC', 'company_name': 'UTI Asset Management Company Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'VBL', 'company_name': 'Varun Beverages Ltd.', 'asset_type': 'stocks', 'sector': 'Fast Moving Consumer Goods'},
    {'symbol': 'VEDL', 'company_name': 'Vedanta Ltd.', 'asset_type': 'stocks', 'sector': 'Metals & Mining'},
    {'symbol': 'VENTIVE', 'company_name': 'Ventive Hospitality Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Services'},
    {'symbol': 'VGUARD', 'company_name': 'V-Guard Industries Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Durables'},
    {'symbol': 'VIJAYA', 'company_name': 'Vijaya Diagnostic Centre Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'VMM', 'company_name': 'Vishal Mega Mart Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Services'},
    {'symbol': 'VOLTAS', 'company_name': 'Voltas Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Durables'},
    {'symbol': 'VTL', 'company_name': 'Vardhman Textiles Ltd.', 'asset_type': 'stocks', 'sector': 'Textiles'},
    {'symbol': 'WAAREEENER', 'company_name': 'Waaree Energies Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'WELCORP', 'company_name': 'Welspun Corp Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'WELSPUNLIV', 'company_name': 'Welspun Living Ltd.', 'asset_type': 'stocks', 'sector': 'Textiles'},
    {'symbol': 'WHIRLPOOL', 'company_name': 'Whirlpool of India Ltd.', 'asset_type': 'stocks', 'sector': 'Consumer Durables'},
    {'symbol': 'WIPRO', 'company_name': 'Wipro Ltd.', 'asset_type': 'stocks', 'sector': 'Information Technology'},
    {'symbol': 'WOCKPHARMA', 'company_name': 'Wockhardt Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
    {'symbol': 'YESBANK', 'company_name': 'Yes Bank Ltd.', 'asset_type': 'stocks', 'sector': 'Financial Services'},
    {'symbol': 'ZEEL', 'company_name': 'Zee Entertainment Enterprises Ltd.', 'asset_type': 'stocks', 'sector': 'Media Entertainment & Publication'},
    {'symbol': 'ZENSARTECH', 'company_name': 'Zensar Technolgies Ltd.', 'asset_type': 'stocks', 'sector': 'Information Technology'},
    {'symbol': 'ZENTEC', 'company_name': 'Zen Technologies Ltd.', 'asset_type': 'stocks', 'sector': 'Capital Goods'},
    {'symbol': 'ZFCVINDIA', 'company_name': 'ZF Commercial Vehicle Control Systems India Ltd.', 'asset_type': 'stocks', 'sector': 'Automobile and Auto Components'},
    {'symbol': 'ZYDUSLIFE', 'company_name': 'Zydus Lifesciences Ltd.', 'asset_type': 'stocks', 'sector': 'Healthcare'},
]