-- Research List Seed: 501 stocks
-- Generated from dev DB for Railway import

INSERT INTO research_list
  (symbol, company_name, asset_type, sector,
   i_score, recommendation, confidence,
   qualitative_score, quantitative_score, search_score, trend_score,
   current_price, previous_close, price_change_pct,
   recommendation_summary, is_active, tenant_id, computation_source,
   created_at, updated_at)
VALUES
  ('360ONE', '360 ONE WAM Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('3MINDIA', '3M India Ltd.', 'stocks', 'Diversified', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('AADHARHFC', 'Aadhar Housing Finance Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('AARTIIND', 'Aarti Industries Ltd.', 'stocks', 'Chemicals', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('AAVAS', 'Aavas Financiers Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ABB', 'ABB India Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ABBOTINDIA', 'Abbott India Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ABCAPITAL', 'Aditya Birla Capital Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ABFRL', 'Aditya Birla Fashion and Retail Ltd.', 'stocks', 'Consumer Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ABLBL', 'Aditya Birla Lifestyle Brands Ltd.', 'stocks', 'Consumer Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ABREL', 'Aditya Birla Real Estate Ltd.', 'stocks', 'Forest Materials', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ABSLAMC', 'Aditya Birla Sun Life AMC Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ACC', 'ACC Ltd.', 'stocks', 'Construction Materials', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ACE', 'Action Construction Equipment Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ACMESOLAR', 'ACME Solar Holdings Ltd.', 'stocks', 'Power', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ADANIENSOL', 'Adani Energy Solutions Ltd.', 'stocks', 'Power', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ADANIENT', 'Adani Enterprises Ltd.', 'stocks', 'Metals & Mining', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ADANIGREEN', 'Adani Green Energy Ltd.', 'stocks', 'Power', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ADANIPORTS', 'Adani Ports and Special Economic Zone Ltd.', 'stocks', 'Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ADANIPOWER', 'Adani Power Ltd.', 'stocks', 'Power', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('AEGISLOG', 'Aegis Logistics Ltd.', 'stocks', 'Oil Gas & Consumable Fuels', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('AEGISVOPAK', 'Aegis Vopak Terminals Ltd.', 'stocks', 'Oil Gas & Consumable Fuels', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('AFCONS', 'Afcons Infrastructure Ltd.', 'stocks', 'Construction', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('AFFLE', 'Affle 3i Ltd.', 'stocks', 'Information Technology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('AGARWALEYE', 'Dr. Agarwal''s Health Care Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('AIAENG', 'AIA Engineering Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('AIIL', 'Authum Investment & Infrastructure Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('AJANTPHARM', 'Ajanta Pharmaceuticals Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('AKUMS', 'Akums Drugs and Pharmaceuticals Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('AKZOINDIA', 'Akzo Nobel India Ltd.', 'stocks', 'Consumer Durables', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ALKEM', 'Alkem Laboratories Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ALKYLAMINE', 'Alkyl Amines Chemicals Ltd.', 'stocks', 'Chemicals', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ALOKINDS', 'Alok Industries Ltd.', 'stocks', 'Textiles', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('AMBER', 'Amber Enterprises India Ltd.', 'stocks', 'Consumer Durables', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('AMBUJACEM', 'Ambuja Cements Ltd.', 'stocks', 'Construction Materials', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ANANDRATHI', 'Anand Rathi Wealth Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ANANTRAJ', 'Anant Raj Ltd.', 'stocks', 'Realty', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ANGELONE', 'Angel One Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('APARINDS', 'Apar Industries Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('APLAPOLLO', 'APL Apollo Tubes Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('APLLTD', 'Alembic Pharmaceuticals Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('APOLLOHOSP', 'Apollo Hospitals Enterprise Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('APOLLOTYRE', 'Apollo Tyres Ltd.', 'stocks', 'Automobile and Auto Components', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('APTUS', 'Aptus Value Housing Finance India Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ARE&M', 'Amara Raja Energy & Mobility Ltd.', 'stocks', 'Automobile and Auto Components', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ASAHIINDIA', 'Asahi India Glass Ltd.', 'stocks', 'Automobile and Auto Components', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ASHOKLEY', 'Ashok Leyland Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ASIANPAINT', 'Asian Paints Ltd.', 'stocks', 'Consumer Durables', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ASTERDM', 'Aster DM Healthcare Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ASTRAL', 'Astral Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ASTRAZEN', 'AstraZenca Pharma India Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ATGL', 'Adani Total Gas Ltd.', 'stocks', 'Oil Gas & Consumable Fuels', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ATHERENERG', 'Ather Energy Ltd.', 'stocks', 'Automobile and Auto Components', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ATUL', 'Atul Ltd.', 'stocks', 'Chemicals', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('AUBANK', 'AU Small Finance Bank Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('AUROPHARMA', 'Aurobindo Pharma Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('AWL', 'AWL Agri Business Ltd.', 'stocks', 'Fast Moving Consumer Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('AXISBANK', 'Axis Bank Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('BAJAJ-AUTO', 'Bajaj Auto Ltd.', 'stocks', 'Automobile and Auto Components', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('BAJAJFINSV', 'Bajaj Finserv Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('BAJAJHFL', 'Bajaj Housing Finance Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('BAJAJHLDNG', 'Bajaj Holdings & Investment Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('BAJFINANCE', 'Bajaj Finance Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('BALKRISIND', 'Balkrishna Industries Ltd.', 'stocks', 'Automobile and Auto Components', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('BALRAMCHIN', 'Balrampur Chini Mills Ltd.', 'stocks', 'Fast Moving Consumer Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('BANDHANBNK', 'Bandhan Bank Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('BANKBARODA', 'Bank of Baroda', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('BANKINDIA', 'Bank of India', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('BASF', 'BASF India Ltd.', 'stocks', 'Chemicals', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('BATAINDIA', 'Bata India Ltd.', 'stocks', 'Consumer Durables', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('BAYERCROP', 'Bayer Cropscience Ltd.', 'stocks', 'Chemicals', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('BBTC', 'Bombay Burmah Trading Corporation Ltd.', 'stocks', 'Fast Moving Consumer Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('BDL', 'Bharat Dynamics Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('BEL', 'Bharat Electronics Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('BEML', 'BEML Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('BERGEPAINT', 'Berger Paints India Ltd.', 'stocks', 'Consumer Durables', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('BHARATFORG', 'Bharat Forge Ltd.', 'stocks', 'Automobile and Auto Components', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('BHARTIARTL', 'Bharti Airtel Ltd.', 'stocks', 'Telecommunication', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('BHARTIHEXA', 'Bharti Hexacom Ltd.', 'stocks', 'Telecommunication', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('BHEL', 'Bharat Heavy Electricals Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('BIKAJI', 'Bikaji Foods International Ltd.', 'stocks', 'Fast Moving Consumer Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('BIOCON', 'Biocon Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('BLS', 'BLS International Services Ltd.', 'stocks', 'Consumer Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('BLUEDART', 'Blue Dart Express Ltd.', 'stocks', 'Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('BLUEJET', 'Blue Jet Healthcare Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('BLUESTARCO', 'Blue Star Ltd.', 'stocks', 'Consumer Durables', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('BOSCHLTD', 'Bosch Ltd.', 'stocks', 'Automobile and Auto Components', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('BPCL', 'Bharat Petroleum Corporation Ltd.', 'stocks', 'Oil Gas & Consumable Fuels', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('BRIGADE', 'Brigade Enterprises Ltd.', 'stocks', 'Realty', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('BRITANNIA', 'Britannia Industries Ltd.', 'stocks', 'Fast Moving Consumer Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('BSE', 'BSE Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('BSOFT', 'Birlasoft Ltd.', 'stocks', 'Information Technology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('CAMPUS', 'Campus Activewear Ltd.', 'stocks', 'Consumer Durables', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('CAMS', 'Computer Age Management Services Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('CANBK', 'Canara Bank', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('CANFINHOME', 'Can Fin Homes Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('CAPLIPOINT', 'Caplin Point Laboratories Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('CARBORUNIV', 'Carborundum Universal Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('CASTROLIND', 'Castrol India Ltd.', 'stocks', 'Oil Gas & Consumable Fuels', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('CCL', 'CCL Products (I) Ltd.', 'stocks', 'Fast Moving Consumer Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('CDSL', 'Central Depository Services (India) Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('CEATLTD', 'Ceat Ltd.', 'stocks', 'Automobile and Auto Components', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('CENTRALBK', 'Central Bank of India', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('CENTURYPLY', 'Century Plyboards (India) Ltd.', 'stocks', 'Consumer Durables', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('CERA', 'Cera Sanitaryware Ltd', 'stocks', 'Consumer Durables', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('CESC', 'CESC Ltd.', 'stocks', 'Power', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('CGCL', 'Capri Global Capital Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('CGPOWER', 'CG Power and Industrial Solutions Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('CHALET', 'Chalet Hotels Ltd.', 'stocks', 'Consumer Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('CHAMBLFERT', 'Chambal Fertilizers & Chemicals Ltd.', 'stocks', 'Chemicals', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('CHENNPETRO', 'Chennai Petroleum Corporation Ltd.', 'stocks', 'Oil Gas & Consumable Fuels', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('CHOICEIN', 'Choice International Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('CHOLAFIN', 'Cholamandalam Investment and Finance Company Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('CHOLAHLDNG', 'Cholamandalam Financial Holdings Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('CIPLA', 'Cipla Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('CLEAN', 'Clean Science and Technology Ltd.', 'stocks', 'Chemicals', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('COALINDIA', 'Coal India Ltd.', 'stocks', 'Oil Gas & Consumable Fuels', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('COCHINSHIP', 'Cochin Shipyard Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('COFORGE', 'Coforge Ltd.', 'stocks', 'Information Technology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('COHANCE', 'Cohance Lifesciences Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('COLPAL', 'Colgate Palmolive (India) Ltd.', 'stocks', 'Fast Moving Consumer Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('CONCOR', 'Container Corporation of India Ltd.', 'stocks', 'Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('CONCORDBIO', 'Concord Biotech Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('COROMANDEL', 'Coromandel International Ltd.', 'stocks', 'Chemicals', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('CRAFTSMAN', 'Craftsman Automation Ltd.', 'stocks', 'Automobile and Auto Components', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('CREDITACC', 'CreditAccess Grameen Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('CRISIL', 'CRISIL Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('CROMPTON', 'Crompton Greaves Consumer Electricals Ltd.', 'stocks', 'Consumer Durables', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('CUB', 'City Union Bank Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('CUMMINSIND', 'Cummins India Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('CYIENT', 'Cyient Ltd.', 'stocks', 'Information Technology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('DABUR', 'Dabur India Ltd.', 'stocks', 'Fast Moving Consumer Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('DALBHARAT', 'Dalmia Bharat Ltd.', 'stocks', 'Construction Materials', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('DATAPATTNS', 'Data Patterns (India) Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('DBREALTY', 'Valor Estate Ltd.', 'stocks', 'Consumer Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('DCMSHRIRAM', 'DCM Shriram Ltd.', 'stocks', 'Diversified', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('DEEPAKFERT', 'Deepak Fertilisers & Petrochemicals Corp. Ltd.', 'stocks', 'Chemicals', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('DEEPAKNTR', 'Deepak Nitrite Ltd.', 'stocks', 'Chemicals', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('DELHIVERY', 'Delhivery Ltd.', 'stocks', 'Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('DEVYANI', 'Devyani International Ltd.', 'stocks', 'Consumer Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('DIVISLAB', 'Divi''s Laboratories Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('DIXON', 'Dixon Technologies (India) Ltd.', 'stocks', 'Consumer Durables', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('DLF', 'DLF Ltd.', 'stocks', 'Realty', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('DMART', 'Avenue Supermarts Ltd.', 'stocks', 'Consumer Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('DOMS', 'DOMS Industries Ltd.', 'stocks', 'Fast Moving Consumer Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('DRREDDY', 'Dr. Reddy''s Laboratories Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('DUMMYHDLVR', 'Dummy Hindustan Unilever Ltd.', 'stocks', 'Fast Moving Consumer Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ECLERX', 'eClerx Services Ltd.', 'stocks', 'Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('EICHERMOT', 'Eicher Motors Ltd.', 'stocks', 'Automobile and Auto Components', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('EIDPARRY', 'E.I.D. Parry (India) Ltd.', 'stocks', 'Fast Moving Consumer Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('EIHOTEL', 'EIH Ltd.', 'stocks', 'Consumer Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ELECON', 'Elecon Engineering Co. Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ELGIEQUIP', 'Elgi Equipments Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('EMAMILTD', 'Emami Ltd.', 'stocks', 'Fast Moving Consumer Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('EMCURE', 'Emcure Pharmaceuticals Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ENDURANCE', 'Endurance Technologies Ltd.', 'stocks', 'Automobile and Auto Components', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ENGINERSIN', 'Engineers India Ltd.', 'stocks', 'Construction', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ENRIN', 'Siemens Energy India Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ERIS', 'Eris Lifesciences Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ESCORTS', 'Escorts Kubota Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ETERNAL', 'Eternal Ltd.', 'stocks', 'Consumer Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('EXIDEIND', 'Exide Industries Ltd.', 'stocks', 'Automobile and Auto Components', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('FACT', 'Fertilisers and Chemicals Travancore Ltd.', 'stocks', 'Chemicals', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('FEDERALBNK', 'Federal Bank Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('FINCABLES', 'Finolex Cables Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('FINPIPE', 'Finolex Industries Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('FIRSTCRY', 'Brainbees Solutions Ltd.', 'stocks', 'Consumer Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('FIVESTAR', 'Five-Star Business Finance Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('FLUOROCHEM', 'Gujarat Fluorochemicals Ltd.', 'stocks', 'Chemicals', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('FORCEMOT', 'Force Motors Ltd.', 'stocks', 'Automobile and Auto Components', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('FORTIS', 'Fortis Healthcare Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('FSL', 'Firstsource Solutions Ltd.', 'stocks', 'Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('GAIL', 'GAIL (India) Ltd.', 'stocks', 'Oil Gas & Consumable Fuels', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('GESHIP', 'Great Eastern Shipping Co. Ltd.', 'stocks', 'Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('GICRE', 'General Insurance Corporation of India', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('GILLETTE', 'Gillette India Ltd.', 'stocks', 'Fast Moving Consumer Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('GLAND', 'Gland Pharma Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('GLAXO', 'Glaxosmithkline Pharmaceuticals Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('GLENMARK', 'Glenmark Pharmaceuticals Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('GMDCLTD', 'Gujarat Mineral Development Corporation Ltd.', 'stocks', 'Metals & Mining', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('GMRAIRPORT', 'GMR Airports Ltd.', 'stocks', 'Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('GODFRYPHLP', 'Godfrey Phillips India Ltd.', 'stocks', 'Fast Moving Consumer Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('GODIGIT', 'Go Digit General Insurance Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('GODREJAGRO', 'Godrej Agrovet Ltd.', 'stocks', 'Fast Moving Consumer Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('GODREJCP', 'Godrej Consumer Products Ltd.', 'stocks', 'Fast Moving Consumer Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('GODREJIND', 'Godrej Industries Ltd.', 'stocks', 'Diversified', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('GODREJPROP', 'Godrej Properties Ltd.', 'stocks', 'Realty', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('GPIL', 'Godawari Power & Ispat Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('GRANULES', 'Granules India Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('GRAPHITE', 'Graphite India Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('GRASIM', 'Grasim Industries Ltd.', 'stocks', 'Construction Materials', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('GRAVITA', 'Gravita India Ltd.', 'stocks', 'Metals & Mining', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('GRSE', 'Garden Reach Shipbuilders & Engineers Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('GSPL', 'Gujarat State Petronet Ltd.', 'stocks', 'Oil Gas & Consumable Fuels', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('GUJGASLTD', 'Gujarat Gas Ltd.', 'stocks', 'Oil Gas & Consumable Fuels', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('GVT&D', 'GE Vernova T&D India Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('HAL', 'Hindustan Aeronautics Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('HAPPSTMNDS', 'Happiest Minds Technologies Ltd.', 'stocks', 'Information Technology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('HAVELLS', 'Havells India Ltd.', 'stocks', 'Consumer Durables', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('HBLENGINE', 'HBL Engineering Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('HCLTECH', 'HCL Technologies Ltd.', 'stocks', 'Information Technology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('HDFCAMC', 'HDFC Asset Management Company Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('HDFCBANK', 'HDFC Bank Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('HDFCLIFE', 'HDFC Life Insurance Company Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('HEG', 'H.E.G. Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('HEROMOTOCO', 'Hero MotoCorp Ltd.', 'stocks', 'Automobile and Auto Components', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('HEXT', 'Hexaware Technologies Ltd.', 'stocks', 'Information Technology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('HFCL', 'HFCL Ltd.', 'stocks', 'Telecommunication', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('HINDALCO', 'Hindalco Industries Ltd.', 'stocks', 'Metals & Mining', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('HINDCOPPER', 'Hindustan Copper Ltd.', 'stocks', 'Metals & Mining', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('HINDPETRO', 'Hindustan Petroleum Corporation Ltd.', 'stocks', 'Oil Gas & Consumable Fuels', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('HINDUNILVR', 'Hindustan Unilever Ltd.', 'stocks', 'Fast Moving Consumer Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('HINDZINC', 'Hindustan Zinc Ltd.', 'stocks', 'Metals & Mining', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('HOMEFIRST', 'Home First Finance Company India Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('HONASA', 'Honasa Consumer Ltd.', 'stocks', 'Fast Moving Consumer Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('HONAUT', 'Honeywell Automation India Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('HSCL', 'Himadri Speciality Chemical Ltd.', 'stocks', 'Chemicals', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('HUDCO', 'Housing & Urban Development Corporation Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('HYUNDAI', 'Hyundai Motor India Ltd.', 'stocks', 'Automobile and Auto Components', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ICICIBANK', 'ICICI Bank Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ICICIGI', 'ICICI Lombard General Insurance Company Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ICICIPRULI', 'ICICI Prudential Life Insurance Company Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('IDBI', 'IDBI Bank Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('IDEA', 'Vodafone Idea Ltd.', 'stocks', 'Telecommunication', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('IDFCFIRSTB', 'IDFC First Bank Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('IEX', 'Indian Energy Exchange Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('IFCI', 'IFCI Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('IGIL', 'International Gemmological Institute (India) Ltd.', 'stocks', 'Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('IGL', 'Indraprastha Gas Ltd.', 'stocks', 'Oil Gas & Consumable Fuels', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('IIFL', 'IIFL Finance Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('IKS', 'Inventurus Knowledge Solutions Ltd.', 'stocks', 'Information Technology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('INDGN', 'Indegene Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('INDHOTEL', 'Indian Hotels Co. Ltd.', 'stocks', 'Consumer Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('INDIACEM', 'India Cements Ltd.', 'stocks', 'Construction Materials', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('INDIAMART', 'Indiamart Intermesh Ltd.', 'stocks', 'Consumer Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('INDIANB', 'Indian Bank', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('INDIGO', 'InterGlobe Aviation Ltd.', 'stocks', 'Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('INDUSINDBK', 'IndusInd Bank Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('INDUSTOWER', 'Indus Towers Ltd.', 'stocks', 'Telecommunication', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('INFY', 'Infosys Ltd.', 'stocks', 'Information Technology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('INOXINDIA', 'INOX India Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('INOXWIND', 'Inox Wind Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('INTELLECT', 'Intellect Design Arena Ltd.', 'stocks', 'Information Technology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('IOB', 'Indian Overseas Bank', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('IOC', 'Indian Oil Corporation Ltd.', 'stocks', 'Oil Gas & Consumable Fuels', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('IPCALAB', 'Ipca Laboratories Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('IRB', 'IRB Infrastructure Developers Ltd.', 'stocks', 'Construction', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('IRCON', 'IRCON International Ltd.', 'stocks', 'Construction', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('IRCTC', 'Indian Railway Catering And Tourism Corporation Ltd.', 'stocks', 'Consumer Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('IREDA', 'Indian Renewable Energy Development Agency Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('IRFC', 'Indian Railway Finance Corporation Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ITC', 'ITC Ltd.', 'stocks', 'Fast Moving Consumer Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ITCHOTELS', 'ITC Hotels Ltd.', 'stocks', 'Consumer Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ITI', 'ITI Ltd.', 'stocks', 'Telecommunication', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('J&KBANK', 'Jammu & Kashmir Bank Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('JBCHEPHARM', 'J.B. Chemicals & Pharmaceuticals Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('JBMA', 'JBM Auto Ltd.', 'stocks', 'Automobile and Auto Components', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('JINDALSAW', 'Jindal Saw Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('JINDALSTEL', 'Jindal Steel Ltd.', 'stocks', 'Metals & Mining', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('JIOFIN', 'Jio Financial Services Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('JKCEMENT', 'J.K. Cement Ltd.', 'stocks', 'Construction Materials', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('JKTYRE', 'JK Tyre & Industries Ltd.', 'stocks', 'Automobile and Auto Components', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('JMFINANCIL', 'JM Financial Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('JPPOWER', 'Jaiprakash Power Ventures Ltd.', 'stocks', 'Power', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('JSL', 'Jindal Stainless Ltd.', 'stocks', 'Metals & Mining', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('JSWCEMENT', 'JSW Cement Ltd.', 'stocks', 'Construction Materials', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('JSWENERGY', 'JSW Energy Ltd.', 'stocks', 'Power', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('JSWINFRA', 'JSW Infrastructure Ltd.', 'stocks', 'Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('JSWSTEEL', 'JSW Steel Ltd.', 'stocks', 'Metals & Mining', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('JUBLFOOD', 'Jubilant Foodworks Ltd.', 'stocks', 'Consumer Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('JUBLINGREA', 'Jubilant Ingrevia Ltd.', 'stocks', 'Chemicals', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('JUBLPHARMA', 'Jubilant Pharmova Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('JWL', 'Jupiter Wagons Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('JYOTHYLAB', 'Jyothy Labs Ltd.', 'stocks', 'Fast Moving Consumer Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('JYOTICNC', 'Jyoti CNC Automation Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('KAJARIACER', 'Kajaria Ceramics Ltd.', 'stocks', 'Consumer Durables', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('KALYANKJIL', 'Kalyan Jewellers India Ltd.', 'stocks', 'Consumer Durables', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('KARURVYSYA', 'Karur Vysya Bank Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('KAYNES', 'Kaynes Technology India Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('KEC', 'Kec International Ltd.', 'stocks', 'Construction', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('KEI', 'KEI Industries Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('KFINTECH', 'Kfin Technologies Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('KIMS', 'Krishna Institute of Medical Sciences Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('KIRLOSBROS', 'Kirloskar Brothers Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('KIRLOSENG', 'Kirloskar Oil Eng Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('KOTAKBANK', 'Kotak Mahindra Bank Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('KPIL', 'Kalpataru Projects International Ltd.', 'stocks', 'Construction', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('KPITTECH', 'KPIT Technologies Ltd.', 'stocks', 'Information Technology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('KPRMILL', 'K.P.R. Mill Ltd.', 'stocks', 'Textiles', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('KSB', 'KSB Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('LALPATHLAB', 'Dr. Lal Path Labs Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('LATENTVIEW', 'Latent View Analytics Ltd.', 'stocks', 'Information Technology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('LAURUSLABS', 'Laurus Labs Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('LEMONTREE', 'Lemon Tree Hotels Ltd.', 'stocks', 'Consumer Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('LICHSGFIN', 'LIC Housing Finance Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('LICI', 'Life Insurance Corporation of India', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('LINDEINDIA', 'Linde India Ltd.', 'stocks', 'Chemicals', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('LLOYDSME', 'Lloyds Metals And Energy Ltd.', 'stocks', 'Metals & Mining', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('LODHA', 'Lodha Developers Ltd.', 'stocks', 'Realty', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('LT', 'Larsen & Toubro Ltd.', 'stocks', 'Construction', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('LTF', 'L&T Finance Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('LTFOODS', 'LT Foods Ltd.', 'stocks', 'Fast Moving Consumer Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('LTIM', 'LTIMindtree Ltd.', 'stocks', 'Information Technology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('LTTS', 'L&T Technology Services Ltd.', 'stocks', 'Information Technology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('LUPIN', 'Lupin Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('M&M', 'Mahindra & Mahindra Ltd.', 'stocks', 'Automobile and Auto Components', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('M&MFIN', 'Mahindra & Mahindra Financial Services Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('MAHABANK', 'Bank of Maharashtra', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('MAHSCOOTER', 'Maharashtra Scooters Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('MAHSEAMLES', 'Maharashtra Seamless Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('MANAPPURAM', 'Manappuram Finance Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('MANKIND', 'Mankind Pharma Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('MANYAVAR', 'Vedant Fashions Ltd.', 'stocks', 'Consumer Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('MAPMYINDIA', 'C.E. Info Systems Ltd.', 'stocks', 'Information Technology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('MARICO', 'Marico Ltd.', 'stocks', 'Fast Moving Consumer Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('MARUTI', 'Maruti Suzuki India Ltd.', 'stocks', 'Automobile and Auto Components', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('MAXHEALTH', 'Max Healthcare Institute Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('MAZDOCK', 'Mazagoan Dock Shipbuilders Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('MCX', 'Multi Commodity Exchange of India Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('MEDANTA', 'Global Health Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('METROPOLIS', 'Metropolis Healthcare Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('MFSL', 'Max Financial Services Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('MGL', 'Mahanagar Gas Ltd.', 'stocks', 'Oil Gas & Consumable Fuels', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('MINDACORP', 'Minda Corporation Ltd.', 'stocks', 'Automobile and Auto Components', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('MMTC', 'MMTC Ltd.', 'stocks', 'Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('MOTHERSON', 'Samvardhana Motherson International Ltd.', 'stocks', 'Automobile and Auto Components', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('MOTILALOFS', 'Motilal Oswal Financial Services Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('MPHASIS', 'MphasiS Ltd.', 'stocks', 'Information Technology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('MRF', 'MRF Ltd.', 'stocks', 'Automobile and Auto Components', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('MRPL', 'Mangalore Refinery & Petrochemicals Ltd.', 'stocks', 'Oil Gas & Consumable Fuels', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('MSUMI', 'Motherson Sumi Wiring India Ltd.', 'stocks', 'Automobile and Auto Components', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('MUTHOOTFIN', 'Muthoot Finance Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('NAM-INDIA', 'Nippon Life India Asset Management Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('NATCOPHARM', 'NATCO Pharma Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('NATIONALUM', 'National Aluminium Co. Ltd.', 'stocks', 'Metals & Mining', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('NAUKRI', 'Info Edge (India) Ltd.', 'stocks', 'Consumer Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('NAVA', 'Nava Ltd.', 'stocks', 'Power', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('NAVINFLUOR', 'Navin Fluorine International Ltd.', 'stocks', 'Chemicals', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('NBCC', 'NBCC (India) Ltd.', 'stocks', 'Construction', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('NCC', 'NCC Ltd.', 'stocks', 'Construction', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('NESTLEIND', 'Nestle India Ltd.', 'stocks', 'Fast Moving Consumer Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('NETWEB', 'Netweb Technologies India Ltd.', 'stocks', 'Information Technology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('NEULANDLAB', 'Neuland Laboratories Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('NEWGEN', 'Newgen Software Technologies Ltd.', 'stocks', 'Information Technology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('NH', 'Narayana Hrudayalaya Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('NHPC', 'NHPC Ltd.', 'stocks', 'Power', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('NIACL', 'The New India Assurance Company Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('NIVABUPA', 'Niva Bupa Health Insurance Company Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('NLCINDIA', 'NLC India Ltd.', 'stocks', 'Power', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('NMDC', 'NMDC Ltd.', 'stocks', 'Metals & Mining', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('NSLNISP', 'NMDC Steel Ltd.', 'stocks', 'Metals & Mining', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('NTPC', 'NTPC Ltd.', 'stocks', 'Power', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('NTPCGREEN', 'NTPC Green Energy Ltd.', 'stocks', 'Power', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('NUVAMA', 'Nuvama Wealth Management Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('NUVOCO', 'Nuvoco Vistas Corporation Ltd.', 'stocks', 'Construction Materials', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('NYKAA', 'FSN E-Commerce Ventures Ltd.', 'stocks', 'Consumer Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('OBEROIRLTY', 'Oberoi Realty Ltd.', 'stocks', 'Realty', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('OFSS', 'Oracle Financial Services Software Ltd.', 'stocks', 'Information Technology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('OIL', 'Oil India Ltd.', 'stocks', 'Oil Gas & Consumable Fuels', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('OLAELEC', 'Ola Electric Mobility Ltd.', 'stocks', 'Automobile and Auto Components', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('OLECTRA', 'Olectra Greentech Ltd.', 'stocks', 'Automobile and Auto Components', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ONESOURCE', 'Onesource Specialty Pharma Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ONGC', 'Oil & Natural Gas Corporation Ltd.', 'stocks', 'Oil Gas & Consumable Fuels', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('PAGEIND', 'Page Industries Ltd.', 'stocks', 'Textiles', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('PATANJALI', 'Patanjali Foods Ltd.', 'stocks', 'Fast Moving Consumer Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('PAYTM', 'One 97 Communications Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('PCBL', 'PCBL Chemical Ltd.', 'stocks', 'Chemicals', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('PERSISTENT', 'Persistent Systems Ltd.', 'stocks', 'Information Technology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('PETRONET', 'Petronet LNG Ltd.', 'stocks', 'Oil Gas & Consumable Fuels', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('PFC', 'Power Finance Corporation Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('PFIZER', 'Pfizer Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('PGEL', 'PG Electroplast Ltd.', 'stocks', 'Consumer Durables', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('PGHH', 'Procter & Gamble Hygiene & Health Care Ltd.', 'stocks', 'Fast Moving Consumer Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('PHOENIXLTD', 'Phoenix Mills Ltd.', 'stocks', 'Realty', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('PIDILITIND', 'Pidilite Industries Ltd.', 'stocks', 'Chemicals', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('PIIND', 'PI Industries Ltd.', 'stocks', 'Chemicals', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('PNB', 'Punjab National Bank', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('PNBHOUSING', 'PNB Housing Finance Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('POLICYBZR', 'PB Fintech Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('POLYCAB', 'Polycab India Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('POLYMED', 'Poly Medicure Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('POONAWALLA', 'Poonawalla Fincorp Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('POWERGRID', 'Power Grid Corporation of India Ltd.', 'stocks', 'Power', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('POWERINDIA', 'Hitachi Energy India Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('PPLPHARMA', 'Piramal Pharma Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('PRAJIND', 'Praj Industries Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('PREMIERENE', 'Premier Energies Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('PRESTIGE', 'Prestige Estates Projects Ltd.', 'stocks', 'Realty', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('PTCIL', 'PTC Industries Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('PVRINOX', 'PVR INOX Ltd.', 'stocks', 'Media Entertainment & Publication', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('RADICO', 'Radico Khaitan Ltd', 'stocks', 'Fast Moving Consumer Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('RAILTEL', 'Railtel Corporation Of India Ltd.', 'stocks', 'Telecommunication', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('RAINBOW', 'Rainbow Childrens Medicare Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('RAMCOCEM', 'The Ramco Cements Ltd.', 'stocks', 'Construction Materials', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('RBLBANK', 'RBL Bank Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('RCF', 'Rashtriya Chemicals & Fertilizers Ltd.', 'stocks', 'Chemicals', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('RECLTD', 'REC Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('REDINGTON', 'Redington Ltd.', 'stocks', 'Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('RELIANCE', 'Reliance Industries Ltd.', 'stocks', 'Oil Gas & Consumable Fuels', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('RELINFRA', 'Reliance Infrastructure Ltd.', 'stocks', 'Power', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('RHIM', 'RHI MAGNESITA INDIA LTD.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('RITES', 'RITES Ltd.', 'stocks', 'Construction', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('RKFORGE', 'Ramkrishna Forgings Ltd.', 'stocks', 'Automobile and Auto Components', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('RPOWER', 'Reliance Power Ltd.', 'stocks', 'Power', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('RRKABEL', 'R R Kabel Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('RVNL', 'Rail Vikas Nigam Ltd.', 'stocks', 'Construction', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SAGILITY', 'Sagility Ltd.', 'stocks', 'Information Technology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SAIL', 'Steel Authority of India Ltd.', 'stocks', 'Metals & Mining', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SAILIFE', 'Sai Life Sciences Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SAMMAANCAP', 'Sammaan Capital Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SAPPHIRE', 'Sapphire Foods India Ltd.', 'stocks', 'Consumer Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SARDAEN', 'Sarda Energy and Minerals Ltd.', 'stocks', 'Metals & Mining', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SAREGAMA', 'Saregama India Ltd', 'stocks', 'Media Entertainment & Publication', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SBFC', 'SBFC Finance Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SBICARD', 'SBI Cards and Payment Services Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SBILIFE', 'SBI Life Insurance Company Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SBIN', 'State Bank of India', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SCHAEFFLER', 'Schaeffler India Ltd.', 'stocks', 'Automobile and Auto Components', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SCHNEIDER', 'Schneider Electric Infrastructure Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SCI', 'Shipping Corporation of India Ltd.', 'stocks', 'Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SHREECEM', 'Shree Cement Ltd.', 'stocks', 'Construction Materials', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SHRIRAMFIN', 'Shriram Finance Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SHYAMMETL', 'Shyam Metalics and Energy Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SIEMENS', 'Siemens Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SIGNATURE', 'Signatureglobal (India) Ltd.', 'stocks', 'Realty', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SJVN', 'SJVN Ltd.', 'stocks', 'Power', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SOBHA', 'Sobha Ltd.', 'stocks', 'Realty', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SOLARINDS', 'Solar Industries India Ltd.', 'stocks', 'Chemicals', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SONACOMS', 'Sona BLW Precision Forgings Ltd.', 'stocks', 'Automobile and Auto Components', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SONATSOFTW', 'Sonata Software Ltd.', 'stocks', 'Information Technology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SRF', 'SRF Ltd.', 'stocks', 'Chemicals', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('STARHEALTH', 'Star Health and Allied Insurance Company Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SUMICHEM', 'Sumitomo Chemical India Ltd.', 'stocks', 'Chemicals', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SUNDARMFIN', 'Sundaram Finance Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SUNDRMFAST', 'Sundram Fasteners Ltd.', 'stocks', 'Automobile and Auto Components', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SUNPHARMA', 'Sun Pharmaceutical Industries Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SUNTV', 'Sun TV Network Ltd.', 'stocks', 'Media Entertainment & Publication', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SUPREMEIND', 'Supreme Industries Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SUZLON', 'Suzlon Energy Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SWANCORP', 'Swan Corp Ltd.', 'stocks', 'Chemicals', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SWIGGY', 'Swiggy Ltd.', 'stocks', 'Consumer Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SYNGENE', 'Syngene International Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('SYRMA', 'Syrma SGS Technology Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('TARIL', 'Transformers And Rectifiers (India) Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('TATACHEM', 'Tata Chemicals Ltd.', 'stocks', 'Chemicals', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('TATACOMM', 'Tata Communications Ltd.', 'stocks', 'Telecommunication', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('TATACONSUM', 'Tata Consumer Products Ltd.', 'stocks', 'Fast Moving Consumer Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('TATAELXSI', 'Tata Elxsi Ltd.', 'stocks', 'Information Technology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('TATAINVEST', 'Tata Investment Corporation Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('TATAPOWER', 'Tata Power Co. Ltd.', 'stocks', 'Power', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('TATASTEEL', 'Tata Steel Ltd.', 'stocks', 'Metals & Mining', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('TATATECH', 'Tata Technologies Ltd.', 'stocks', 'Information Technology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('TBOTEK', 'TBO Tek Ltd.', 'stocks', 'Consumer Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('TCS', 'Tata Consultancy Services Ltd.', 'stocks', 'Information Technology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('TECHM', 'Tech Mahindra Ltd.', 'stocks', 'Information Technology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('TECHNOE', 'Techno Electric & Engineering Company Ltd.', 'stocks', 'Construction', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('TEJASNET', 'Tejas Networks Ltd.', 'stocks', 'Telecommunication', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('THELEELA', 'Leela Palaces Hotels & Resorts Ltd.', 'stocks', 'Consumer Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('THERMAX', 'Thermax Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('TIINDIA', 'Tube Investments of India Ltd.', 'stocks', 'Automobile and Auto Components', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('TIMKEN', 'Timken India Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('TITAGARH', 'Titagarh Rail Systems Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('TITAN', 'Titan Company Ltd.', 'stocks', 'Consumer Durables', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('TMPV', 'Tata Motors Passenger Vehicles Ltd.', 'stocks', 'Automobile and Auto Components', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('TORNTPHARM', 'Torrent Pharmaceuticals Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('TORNTPOWER', 'Torrent Power Ltd.', 'stocks', 'Power', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('TRENT', 'Trent Ltd.', 'stocks', 'Consumer Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('TRIDENT', 'Trident Ltd.', 'stocks', 'Textiles', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('TRITURBINE', 'Triveni Turbine Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('TRIVENI', 'Triveni Engineering & Industries Ltd.', 'stocks', 'Fast Moving Consumer Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('TTML', 'Tata Teleservices (Maharashtra) Ltd.', 'stocks', 'Telecommunication', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('TVSMOTOR', 'TVS Motor Company Ltd.', 'stocks', 'Automobile and Auto Components', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('UBL', 'United Breweries Ltd.', 'stocks', 'Fast Moving Consumer Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('UCOBANK', 'UCO Bank', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ULTRACEMCO', 'UltraTech Cement Ltd.', 'stocks', 'Construction Materials', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('UNIONBANK', 'Union Bank of India', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('UNITDSPR', 'United Spirits Ltd.', 'stocks', 'Fast Moving Consumer Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('UNOMINDA', 'UNO Minda Ltd.', 'stocks', 'Automobile and Auto Components', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('UPL', 'UPL Ltd.', 'stocks', 'Chemicals', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('USHAMART', 'Usha Martin Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('UTIAMC', 'UTI Asset Management Company Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('VBL', 'Varun Beverages Ltd.', 'stocks', 'Fast Moving Consumer Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('VEDL', 'Vedanta Ltd.', 'stocks', 'Metals & Mining', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('VENTIVE', 'Ventive Hospitality Ltd.', 'stocks', 'Consumer Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('VGUARD', 'V-Guard Industries Ltd.', 'stocks', 'Consumer Durables', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('VIJAYA', 'Vijaya Diagnostic Centre Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('VMM', 'Vishal Mega Mart Ltd.', 'stocks', 'Consumer Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('VOLTAS', 'Voltas Ltd.', 'stocks', 'Consumer Durables', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('VTL', 'Vardhman Textiles Ltd.', 'stocks', 'Textiles', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('WAAREEENER', 'Waaree Energies Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('WELCORP', 'Welspun Corp Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('WELSPUNLIV', 'Welspun Living Ltd.', 'stocks', 'Textiles', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('WHIRLPOOL', 'Whirlpool of India Ltd.', 'stocks', 'Consumer Durables', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('WIPRO', 'Wipro Ltd.', 'stocks', 'Information Technology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('WOCKPHARMA', 'Wockhardt Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('YESBANK', 'Yes Bank Ltd.', 'stocks', 'Financial Services', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ZEEL', 'Zee Entertainment Enterprises Ltd.', 'stocks', 'Media Entertainment & Publication', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ZENSARTECH', 'Zensar Technolgies Ltd.', 'stocks', 'Information Technology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ZENTEC', 'Zen Technologies Ltd.', 'stocks', 'Capital Goods', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ZFCVINDIA', 'ZF Commercial Vehicle Control Systems India Ltd.', 'stocks', 'Automobile and Auto Components', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW()),
  ('ZYDUSLIFE', 'Zydus Lifesciences Ltd.', 'stocks', 'Healthcare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'live', 'nightly', NOW(), NOW())
ON CONFLICT (symbol) DO UPDATE SET
  company_name = EXCLUDED.company_name,
  asset_type = EXCLUDED.asset_type,
  sector = EXCLUDED.sector,
  is_active = EXCLUDED.is_active,
  tenant_id = EXCLUDED.tenant_id,
  updated_at = NOW();

SELECT COUNT(*) as seeded_count FROM research_list WHERE is_active = true;